analyses:
  
  # analysis_tool1:
  #   analysis_name1:
  #     arg1: "value"
  #     arg2: "value"

  #   analysis_name2:
  #     arg1: "value"
  #     arg2: "value"

  beast:
    intro:
      xml: "resources/beast_xml/primate-mtDNA.xml"
      command: "beast"
      action: ""
      time: 7200
      mem_mb: 4096
      threads: 10
      burnin: 10
      chains: 2


