# ------------------------------------------------------------------------------
#          ---        
#        / o o \    Snakemake workflow phylo-BEAST
#        V\ Y /V    Config file snakemake-phylo-BEAST
#    (\   / - \     
#     )) /    |     
#     ((/__) ||     Code by Ceci VA 
# ------------------------------------------------------------------------------

# use snakemake templates

run: 
  intro:
    dataset: ["example"]
    action: "resume"
    user_check: FALSE

  # intro_bis:
  #   dataset: ["example_structured", "primates_structured"]
  #   action: "resume"
  #   user_check: TRUE

config_datasets: "config/datasets.yaml"
config_analyses: "config/analyses.yaml"

target_files: ["log", "trees", "MCC.tree", "CCD0.tree"]

lapis:
  seq_id: "genbankAccession" 
  database: "open" # gisaid or open
  batch_size: 50

align:
  parameters: 

mask:
  mask_from_beginning: 100
  mask_from_end: 200
  mask_sites: [21846, 21987, 22992, 23012, 23063, 23604, 24410]

beast:
  command: "beast"
  user_check: FALSE
  time: 7200
  mem_mb: 4096
  threads: 2
  burnin: 10
  chains: 1

logcombiner:
  command:  "logcombiner"
  resample: 10000

treeannotator:
  command:  "treeannotator"
  heights: "median"
