# ------------------------------------------------------------------------------
#          ---        
#        / o o \    Snakemake workflow phylo-BEAST
#        V\ Y /V    Config file snakemake-phylo-BEAST
#    (\   / - \     
#     )) /    |     
#     ((/__) ||     Code by Ceci VA 
# ------------------------------------------------------------------------------

# use snakemake templates

run: 
  intro:
    dataset: ["primates"]
    action: "resume"
    user_check: FALSE

  # intro_bis:
  #   dataset: ["example_structured", "primates_structured"]
  #   action: "resume"
  #   user_check: TRUE

config_datasets: "config/datasets.yaml"
config_analyses: "config/analyses.yaml"

target_files: ["log", "trees"]
#   # iqtree: ["treefile", "png"]
#   # treetime: ["nexus", "png"]
#   beast: ["log", "trees"]


# ------------- WIP


lapis:
  seq_id: "genbankAccession" 
  database: "open" # gisaid or open
  batch_size: 50

# # align:
# #   parameters:

# mask:
#   mask_from_beginning: 100
#   mask_from_end: 200
#   mask_sites: [21846, 21987, 22992, 23012, 23063, 23604, 24410]

# output:
#   plot_dataset: true
#   plot_tree: true
#   check_ESS: true
#   plot_parameters:
#     - Re
#     - ReAmongDemes
#     - clockRate
# check ESS, if passed MCC tree and parameter plots (user defined parameters)
  # add config file for plotting output
  # check ess of chains already combined, user defined burnin or try different values automatically to maximize ess
  # use ugne's feast class to random initialize the parameters

# run: 
#   # tool:
#     # analysis1: 
#     #   - "dataset1"
#     #   - "dataset2"
#     # analysis2:
#     #   - "dataset2"
#   beast:
#     intro:
#     - "primates"

#     intro_bis:
#     - "example_structured"

