datasets:

  primates:
    sequences: "resources/data/primate-mtDNA.nex"

  # covid_lapis:
  #   # replicates: 2
  #   metadata: "lapis"
  #   sequences: "lapis"
  #   select:
  #     country: "Switzerland"
  #     dateFrom: "2021-01-01"
  #     dateTo: "2021-01-15"
    # subsample:
    #   n: 20 #TODO "deme-balanced"
    #   method: "random"


  # dataset1_lapis: 
  #   replicates: 3
  #   structure:
  #     deme1:
  #       select:
  #         nextcladeQcMissingDataScoreFrom: 0
  #         nextcladeQcMissingDataScoreTo: 300
  #         dateFrom: ""
  #         dasteTo: ""
  #       subsample:
  #         n: -1
  #         method: "random" # none, random, weighted or uniform
  #         weights_file: null
  #         include: null
  #         exclude: null
  #     deme2:
  #       select:
  #         nextcladeQcMissingDataScoreFrom: 0
  #         nextcladeQcMissingDataScoreTo: 300
  #         dateFrom: ""
  #         dateTo: ""
        
  # dataset1: 
  #   select: "all"      
  #   filter: true
  #   qc:
  #     missing_proportion: 0.1
  #     min_length: 29000
  #   replicates: 3
  #   subsample:
  #     n: -1
  #     method: "random" # none, random, weighted or uniform
  #     weights_file: null
  #     include: null
  #     exclude: null

  # dataset1_structured:
  #   replicates: 3
  #   filter: true
  #   structure: 
  #     deme1: # all seqs in metadata from that type
  #       select: 
  #         type: "type1" # for = queries
  #       qc:
  #         missing_proportion: 0.1
  #         min_length: 29000
  #       subsample:
  #         n: 50
  #         method: "random" # none, random, weighted or uniform
  #         weights_file: null
  #         include: null
  #         exclude: null
  #     deme2: 
  #       select:  # from metadata file example 
  #         type: "type2" # for = queries
  #         # date: # for < or > queries
  #         #   min:
  #         #   max:
  #       qc:
  #         missing_proportion: 0.1
  #         min_length: 29000
  #       subsample:
  #         n: -1
  #         method: "random" # none, random, weighted or uniform
  #         weights_file: null
  #         include: null
  #         exclude: null


  # dataset1_structured:
  #   structure: 
  #     deme1: # all seqs in metadata from that type
  #       select:
  #         type: "type1" # for = queries
  #     deme2: 
  #       select: # from metadata file example 
  #         type: "type2" # for = queries
  #         # date: # for < or > queries
  #         #   min:
  #         #   max:
          
        
  # dataset2:
  #   replicates: 3
  #   select: # from metadata file example 
  #       date: # for < or > queries
  #         min:
  #         max:
  #       type: # for = queries
  #   subsample:
  #       n: -1
  #       method: "random" # none, random, weighted or uniform
  #       weights_file: null
  #       include: null
  #       exclude: null

  #   dataset2_structured: # with lapis import
  #   deme1:
  #     select: # lapis import example from id file
  #       ids_file: ""
  #       nextcladeQcMissingDataScoreFrom: 0
  #       nextcladeQcMissingDataScoreTo: 300
  #       dateFrom: ""
  #       dateTo: ""
  #     subsample:
  #       n: -1
  #       # method: "random" # none, random, weighted or uniform
  #       # weights_file: null
  #       include: null
  #       exclude: null
  #       # replicates: 1
        
  #   deme2:
  #     select: # lapis import example with subsample and replicates
  #       ids_file: ""
  #       nextcladeQcMissingDataScoreFrom: 0
  #       nextcladeQcMissingDataScoreTo: 300
  #       dateFrom: ""
  #       dateTo: ""
  #     subsample:
  #       n: -1
  #       method: "random" # none, random, weighted or uniform
  #       weights_file: null
  #       include: null
  #       exclude: null
  #       replicates: 1
